### PR TITLE
Add animation to Jump In button and fix other issues

### PR DESCRIPTION
**Pull request by V1shvesh**
@ryzokuken 
Jump In buton expands on hover. Lemme know if it looks good.

**Edit 1:**
Fixed Issue #27 . Do take a look.

**Edit 2:**
Fixed Issue #28 .

### CODE REVIEW

**Comment by ryzokuken** [comment]
@V1shvesh where can I preview the website?

**Comment by V1shvesh** [comment]
B A M B O O Z L E D
I haven't set up a website for this... clone it maybe??

**Comment by saranshbarua** [comment]
@V1shvesh you can host it on Github pages for now.

**Comment by ryzokuken** [comment]
Yeah, there's an option in the settings tab.

**Comment by V1shvesh** [comment]
cool... will do that as soon as I get home

**Comment by ryzokuken** [comment]
Awesome! Merging.

**Pull request merged**
