### PR TITLE
Added full list of speakers, a venue section with minor bug fixes

### PR DESCRIPTION
**Pull request by saranshbarua**
@ryzokuken @shivanXI have a look.
[Preview](https://saranshbarua.github.io/osdconf-website/)

### CODE REVIEW

**Comment by shivanXI** [comment]
@saranshbarua few changes are requested:
1. change the background image of the venue map section and use that of drupal's picture which abhishek also mentioned in the group 
2. in footer also add logo of jaypee as well if we are using their name not big one ;) small one will be alright 
3. make 2nd line of address in venue section centre aligned instead of left aligned and you can use any kind of favicon for location as well over there and also please decrease the font size also

**Comment by saranshbarua** [comment]
@shivanXI we are also building a past event's section and will be using that drupal's image. Do you think we should use the same picture twice? I'll do the second and third changes soon.

**Comment by shivanXI** [comment]
OK you can other pictures as well search it from drupal's page

**Comment by saranshbarua** [comment]
@shivanXI Done the minor changes. The images will be added in the next PR once I get them.
Merging this for now.

**Pull request merged**
