### PR TITLE
Added sponsors section and timeline/schedule

### PR DESCRIPTION
**Pull request by saranshbarua**
@shivanXI @ryzokuken I added the sponsor's section. The images are just placeholders now. Also added content which was decided by the team to the about section with few fixes.
[Preview](https://saranshbarua.github.io/osdconf-website/)

### CODE REVIEW

**Comment by ryzokuken** [comment]
My bad: the writeup says "OSDC Conference", but it's OSDConf and I realize OSD Conference sounds a little odd, so you could just replace that with the full name (i.e. Open Source Developers' Conference)

**Comment by saranshbarua** [comment]
@ryzokuken have a look now.

**Comment by saranshbarua** [comment]
@ryzokuken @shivanXI have a look at this one.

**Comment by ryzokuken** [comment]
@saranshbarua the schedule looks really nice, but maybe for a conference it should look kinda different, for example: here is how GitHub Universe's schedule looks (and it looks perfect to me) https://githubuniverse.com/program/

P.S. Now that I look at it, actually you can take away a ton of stuff from this website, it seems to be a great inspiration. We could take a look at the website and use everything they've done as a base and innovate on top of it.

**Comment by shivanXI** [comment]
@saranshbarua  i think @ryzokuken  is saying right we can use that website as a base and innovate on top of it for everything specially for schedule section and secondly please include the gold , silver and platinum sponsor subsection in a sponsor section instead of single sponsor section , it would look more rich to our sponsors as well when they will see it and also more people will be attracted to our conf after seeing this section filled with categorised sponsors which will make this section more clear and stable according to me.

**Pull request merged**
