### PR TITLE
Added box shadow, background overlay, background images in terminal

### PR DESCRIPTION
**Pull request by rajatjain1998**
check it out
Rajat

### CODE REVIEW

**Comment by saranshbarua** [comment]
@rajatjain1998 please include a link to a preview, so that the changes can be analysed visually.

**Comment by rajatjain1998** [comment]
https://rajatjain1998.github.io/osdconf-website/main.html

**Comment by saranshbarua** [comment]
@rajatjain1998 this looks good. One little thing though, when the navbar opens the shape of the nav-background is neither circular nor rectangular. Please correct that. Also if the box shadow can be reduced by a certain amount then it would look just perfect. @ryzokuken @shivanXI need your inputs on this one.

**Comment by rajatjain1998** [comment]
Changes in design:
- Overlay rounded
- Top border to the terminal (light grey) (b/w taskbar and window)
- osdc logo in the background of terminal
- Box shadow opacity reduced

Code changed:
- A new class (.nav-background) containing div is added around <nav> in the main.html
- .nav class 
- .nav-background added in media @ 937px

Compare the code for more info.

**Comment by shivanXI** [comment]
@saranshbarua i noticed 1 thing that the logo of osdconf is not required in it as it is making it look weird according to a normal user which is also hiding the front of main.html as well .....shadow on the terminal based menu is good to go but on the navbar, please set the position of cross as it is coming more right side oriented as compared to the circular background behind it on safari and firefox making it look weird again. Rest of the things are good to go and fine.

**Comment by shivanXI** [comment]
@rajatjain1998 there are some more flaws in it , basically when you are using laptop with HiDPI screens your shadow is not fully covering the whole screen as i have seen you have fixed the border radius to 5px thats why it is not becoming circular on various resolutions...so try to repair this stuff ASAP we are having less time to develop many other things.

**Comment by rajatjain1998** [comment]
Background issue can be solved.
Should I remove the terminal background?

**Pull request closed without merging**
