### PR TITLE
Added main.html

### PR DESCRIPTION
**Pull request by saranshbarua**
Added the main page of the website. Using lorem ipsum for now.

### CODE REVIEW

**Comment by ryzokuken** [comment]
@saranshbarua looks awesome! Please add smoothscrolling on navbar and make the close button the terminal more apparent. (Perhaps display a cross inside it when the user hovers in the window, hinting at the fact that it isn't just a showpiece).

**Comment by saranshbarua** [comment]
@ryzokuken did the changes. Have a look now.

**Comment by shivanXI** [comment]
@saranshbarua  it looks awesome and good to go

**Comment by ryzokuken** [comment]
@saranshbarua merged! Let's start working on the next one.

**Pull request merged**
