### PR TITLE
Footer layout changed

### PR DESCRIPTION
**Pull request by rajatjain1998**
@ryzokuken @saranshbarua Review the footer
Hosted at: https://rajatjain1998.github.io/osdconf-website/main.html

### CODE REVIEW

**Comment by saranshbarua** [comment]
@rajatjain1998 awesome work. Just a small suggestion, the padding bottom and top should be increased in mobile view and a little gap should be there between the social media icons and their title. Correct these changes then we are good to go.

**Comment by rajatjain1998** [comment]
@saranshbarua Job done

**Comment by saranshbarua** [comment]
@rajatjain1998 LGTM, let's get this merged by tonight.

**Comment by saranshbarua** [comment]
Merging this. Let's work on other things now.

**Pull request merged**
